export type { DotShape, PointShapeData } from './types'
export { smoothstep01 } from './smoothstep'
export { MORPH_PERIOD, morphWeightsThreeShapes } from './morphTimeline'
export type { MorphWeights3 } from './morphTimeline'
export { SphereDotShape } from './sphereDotShape'
export type { SphereTangentFrame } from './sphereDotShape'
export { CubeDotShape } from './cubeDotShape'
export { DodecahedronDotShape } from './dodecahedronDotShape'
